In [1]:
import pandas as pd
import os

In [2]:
df_0030 = pd.read_csv("../datasets/schaefcomb_Wang2023Simple_ds000030.tsv", sep = "\t")

In [3]:
df_4302 = pd.read_csv("../datasets/schaefcomb_wang2023SimpleCorrMatrix_ds004302.tsv", sep = "\t")

In [4]:
df_0030

,participant_id,diagnosis,age,gender,corr_1_2,corr_1_3,corr_1_4,corr_1_5,corr_1_6,corr_1_7,...,corr_430_431,corr_430_432,corr_430_433,corr_430_434,corr_431_432,corr_431_433,corr_431_434,corr_432_433,corr_432_434,corr_433_434
0,sub-10882,CONTROL,23,M,0.477547,0.638581,0.392431,0.385388,0.430888,0.255304,...,NaN,-0.141496,0.596675,0.718413,NaN,NaN,NaN,0.048406,-0.216341,0.467097
1,sub-50060,SCHZ,41,M,0.236506,0.409419,0.478803,0.485308,0.549000,NaN,...,NaN,0.193586,0.494809,0.873883,NaN,NaN,NaN,0.105522,0.132032,0.570359
2,sub-11050,CONTROL,48,M,0.648733,0.716660,0.623435,0.564130,0.532980,0.560695,...,NaN,0.072057,0.572596,0.791360,NaN,NaN,NaN,0.172930,-0.043728,0.471718
3,sub-10638,CONTROL,25,F,0.701393,0.483842,0.550997,0.259333,0.616243,0.299283,...,NaN,0.339606,0.570229,0.734769,NaN,NaN,NaN,0.366463,0.268709,0.559248
4,sub-60006,BIPOLAR,22,M,0.692682,0.518877,0.522635,0.606298,0.624548,0.712177,...,NaN,0.176032,0.389019,0.551859,NaN,NaN,NaN,0.348023,0.345641,0.695046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,sub-70069,ADHD,40,M,0.319979,0.363290,0.160323,0.228982,0.192431,0.265252,...,NaN,0.215723,0.334626,0.636630,NaN,NaN,NaN,0.320998,0.199143,0.377266
257,sub-50050,SCHZ,23,M,0.408659,0.625603,0.580818,0.505342,0.594377,0.512560,...,NaN,0.233372,0.801159,0.832692,NaN,NaN,NaN,0.224592,0.060429,0.740576
258,sub-50027,SCHZ,30,F,0.570379,0.185638,0.040868,-0.155433,0.320036,-0.096514,...,NaN,0.151804,0.391141,0.400840,NaN,NaN,NaN,0.173437,0.165881,0.401487
259,sub-60036,BIPOLAR,45,F,0.279543,0.310057,0.397690,0.192092,0.424237,0.266346,...,NaN,0.352575,0.528941,0.742705,NaN,NaN,NaN,0.174238,0.379484,0.630966
260,sub-10471,CONTROL,30,F,0.480046,0.383312,0.472964,0.459167,0.425058,0.480933,...,NaN,0.037242,0.394802,0.685845,NaN,NaN,NaN,0.503367,0.142980,0.393602

In [5]:
df_4302

,participant_id,group,age,gender,corr_1_2,corr_1_3,corr_1_4,corr_1_5,corr_1_6,corr_1_7,...,corr_430_431,corr_430_432,corr_430_433,corr_430_434,corr_431_432,corr_431_433,corr_431_434,corr_432_433,corr_432_434,corr_433_434
0,sub-21,HC,42,male,0.490576,0.517883,0.210354,-0.141498,-0.037986,0.463561,...,NaN,-0.043958,0.241066,0.761991,NaN,NaN,NaN,0.130499,0.042302,0.263245
1,sub-10,HC,36,female,0.530886,0.197037,0.063933,NaN,NaN,0.176366,...,NaN,0.466669,0.419196,0.821153,NaN,NaN,NaN,0.190861,0.382156,0.437156
2,sub-29,AVH-,38,male,0.089402,0.626631,0.331181,0.301076,0.248458,0.322992,...,NaN,0.239342,0.726386,0.840522,NaN,NaN,NaN,0.262178,0.173635,0.652580
3,sub-55,AVH+,44,male,-0.244867,0.221269,-0.024080,0.400658,0.110211,0.059193,...,NaN,0.077383,0.461178,0.668942,NaN,NaN,NaN,0.241547,0.127348,0.546583
4,sub-13,HC,21,male,0.550478,0.115718,0.126624,NaN,NaN,NaN,...,NaN,0.397387,0.618455,0.800655,NaN,NaN,NaN,0.326573,0.380685,0.554728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,sub-02,HC,36,male,0.497591,-0.072319,0.286599,0.211179,0.046972,0.162896,...,NaN,0.142279,0.084813,0.627601,NaN,NaN,NaN,-0.043293,-0.005678,-0.122463
67,sub-23,HC,33,male,0.403252,NaN,0.056611,NaN,NaN,NaN,...,NaN,0.338818,0.316443,NaN,NaN,NaN,NaN,0.043137,NaN,NaN
68,sub-59,AVH+,25,male,0.394448,NaN,0.473294,NaN,NaN,NaN,...,NaN,-0.038448,0.192909,0.841282,NaN,NaN,NaN,0.064823,-0.020702,0.248297
69,sub-66,AVH+,44,male,0.360832,0.532606,0.459539,0.155020,0.352381,NaN,...,NaN,-0.018519,0.327891,0.767205,NaN,NaN,NaN,-0.153182,-0.038251,0.326057
70,sub-48,AVH-,47,female,0.162892,0.485138,-0.057104,NaN,-0.356084,0.229299,...,NaN,0.098565,0.247359,0.551738,NaN,NaN,NaN,0.164035,-0.018472,0.043226

In [6]:
# Création de la colonne diagnosis
df_4302["diagnosis"] = df_4302["group"].map({
    "HC": "CONTROL",
    "AVH-": "SCHZ",
    "AVH+": "SCHZ",
})

df_4302["diagnosis"] = df_4302["diagnosis"].fillna("UNKNOWN")

# Renommer les valeurs de gender
df_4302["gender"] = df_4302["gender"].replace({
    "male": "M",
    "female": "F",
})

# Replacer la colonne diagnosis juste après "group"
cols = list(df_4302.columns)
group_idx = cols.index("group")
# retirer puis réinsérer à la bonne position
cols.insert(group_idx + 1, cols.pop(cols.index("diagnosis")))
df_4302 = df_4302[cols]

In [7]:
df_4302

,participant_id,group,diagnosis,age,gender,corr_1_2,corr_1_3,corr_1_4,corr_1_5,corr_1_6,...,corr_430_431,corr_430_432,corr_430_433,corr_430_434,corr_431_432,corr_431_433,corr_431_434,corr_432_433,corr_432_434,corr_433_434
0,sub-21,HC,CONTROL,42,M,0.490576,0.517883,0.210354,-0.141498,-0.037986,...,NaN,-0.043958,0.241066,0.761991,NaN,NaN,NaN,0.130499,0.042302,0.263245
1,sub-10,HC,CONTROL,36,F,0.530886,0.197037,0.063933,NaN,NaN,...,NaN,0.466669,0.419196,0.821153,NaN,NaN,NaN,0.190861,0.382156,0.437156
2,sub-29,AVH-,SCHZ,38,M,0.089402,0.626631,0.331181,0.301076,0.248458,...,NaN,0.239342,0.726386,0.840522,NaN,NaN,NaN,0.262178,0.173635,0.652580
3,sub-55,AVH+,SCHZ,44,M,-0.244867,0.221269,-0.024080,0.400658,0.110211,...,NaN,0.077383,0.461178,0.668942,NaN,NaN,NaN,0.241547,0.127348,0.546583
4,sub-13,HC,CONTROL,21,M,0.550478,0.115718,0.126624,NaN,NaN,...,NaN,0.397387,0.618455,0.800655,NaN,NaN,NaN,0.326573,0.380685,0.554728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,sub-02,HC,CONTROL,36,M,0.497591,-0.072319,0.286599,0.211179,0.046972,...,NaN,0.142279,0.084813,0.627601,NaN,NaN,NaN,-0.043293,-0.005678,-0.122463
67,sub-23,HC,CONTROL,33,M,0.403252,NaN,0.056611,NaN,NaN,...,NaN,0.338818,0.316443,NaN,NaN,NaN,NaN,0.043137,NaN,NaN
68,sub-59,AVH+,SCHZ,25,M,0.394448,NaN,0.473294,NaN,NaN,...,NaN,-0.038448,0.192909,0.841282,NaN,NaN,NaN,0.064823,-0.020702,0.248297
69,sub-66,AVH+,SCHZ,44,M,0.360832,0.532606,0.459539,0.155020,0.352381,...,NaN,-0.018519,0.327891,0.767205,NaN,NaN,NaN,-0.153182,-0.038251,0.326057
70,sub-48,AVH-,SCHZ,47,F,0.162892,0.485138,-0.057104,NaN,-0.356084,...,NaN,0.098565,0.247359,0.551738,NaN,NaN,NaN,0.164035,-0.018472,0.043226

In [8]:
# Ajouter la colonne site_id avant la concaténation
df_0030.loc[:, "site_id"] = "ds000030"
df_4302.loc[:, "site_id"] = "ds004302"

# Retirer group dans df_4302
df_4302 = df_4302.drop(columns=["group"])

# Retirer les sujets BIPOLAR et ADHD dans df_0030
df_0030 = df_0030[~df_0030["diagnosis"].isin(["BIPOLAR", "ADHD"])]

# Concaténer verticalement
df_all = pd.concat([df_0030, df_4302], ignore_index=True)

# Replacer site_id juste après diagnosis
cols = list(df_all.columns)
diag_idx = cols.index("diagnosis")
cols.insert(diag_idx + 1, cols.pop(cols.index("site_id")))
df_all = df_all[cols]

/tmp/ipykernel_113783/1619019689.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_4302.loc[:, "site_id"] = "ds004302"

In [9]:
df_all

,participant_id,diagnosis,site_id,age,gender,corr_1_2,corr_1_3,corr_1_4,corr_1_5,corr_1_6,...,corr_430_431,corr_430_432,corr_430_433,corr_430_434,corr_431_432,corr_431_433,corr_431_434,corr_432_433,corr_432_434,corr_433_434
0,sub-10882,CONTROL,ds000030,23,M,0.477547,0.638581,0.392431,0.385388,0.430888,...,NaN,-0.141496,0.596675,0.718413,NaN,NaN,NaN,0.048406,-0.216341,0.467097
1,sub-50060,SCHZ,ds000030,41,M,0.236506,0.409419,0.478803,0.485308,0.549000,...,NaN,0.193586,0.494809,0.873883,NaN,NaN,NaN,0.105522,0.132032,0.570359
2,sub-11050,CONTROL,ds000030,48,M,0.648733,0.716660,0.623435,0.564130,0.532980,...,NaN,0.072057,0.572596,0.791360,NaN,NaN,NaN,0.172930,-0.043728,0.471718
3,sub-10638,CONTROL,ds000030,25,F,0.701393,0.483842,0.550997,0.259333,0.616243,...,NaN,0.339606,0.570229,0.734769,NaN,NaN,NaN,0.366463,0.268709,0.559248
4,sub-11068,CONTROL,ds000030,39,M,0.662086,0.502984,0.480033,0.329556,0.730771,...,NaN,0.400493,0.755405,0.886060,NaN,NaN,NaN,0.551971,0.434086,0.783702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,sub-02,CONTROL,ds004302,36,M,0.497591,-0.072319,0.286599,0.211179,0.046972,...,NaN,0.142279,0.084813,0.627601,NaN,NaN,NaN,-0.043293,-0.005678,-0.122463
239,sub-23,CONTROL,ds004302,33,M,0.403252,NaN,0.056611,NaN,NaN,...,NaN,0.338818,0.316443,NaN,NaN,NaN,NaN,0.043137,NaN,NaN
240,sub-59,SCHZ,ds004302,25,M,0.394448,NaN,0.473294,NaN,NaN,...,NaN,-0.038448,0.192909,0.841282,NaN,NaN,NaN,0.064823,-0.020702,0.248297
241,sub-66,SCHZ,ds004302,44,M,0.360832,0.532606,0.459539,0.155020,0.352381,...,NaN,-0.018519,0.327891,0.767205,NaN,NaN,NaN,-0.153182,-0.038251,0.326057
242,sub-48,SCHZ,ds004302,47,F,0.162892,0.485138,-0.057104,NaN,-0.356084,...,NaN,0.098565,0.247359,0.551738,NaN,NaN,NaN,0.164035,-0.018472,0.043226

In [10]:
# Vérifier les diagnostics restants dans df_all
df_all["diagnosis"].value_counts()

diagnosis
CONTROL    147
SCHZ        96
Name: count, dtype: int64

In [11]:
### version sans PCA

import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, roc_auc_score
from tqdm import tqdm

print("Préparation des données...")

# Toutes les colonnes corr_*
all_corr_cols = [c for c in df_all.columns if c.startswith("corr_")]
X_full = df_all[all_corr_cols]

# Garder seulement les colonnes avec au moins une valeur non-NaN
valid_mask = X_full.notna().any(axis=0)
corr_cols = list(X_full.columns[valid_mask])
X = X_full[corr_cols].values

# y = 1 pour SCHZ, 0 pour CONTROL
y = (df_all["diagnosis"] == "SCHZ").astype(int).values

print(f"Nombre de sujets : {len(y)}")
print(f"Nombre total de features corr_* : {len(all_corr_cols)}")
print(f"Nombre de features après retrait des colonnes 100% NaN : {len(corr_cols)}")
print(f"Répartition SCHZ = {y.sum()}, CONTROL = {len(y) - y.sum()}")

# 10 splits stratifiés, seed 42
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

clf = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler(with_mean=True, with_std=True)),
    ("logreg", LogisticRegression(
        penalty="l2",
        solver="saga",
        max_iter=5000,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )),
])

accs = []
aucs = []

print("\nDémarrage du cross-validation 10 splits...\n")

for split_id, (train_idx, test_idx) in enumerate(tqdm(cv.split(X, y), total=10), start=1):

    print(f"\n=== Split {split_id} / 10 ===")

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    print("  - Entraînement du modèle (imputation + scaling + logreg)...")
    clf.fit(X_train, y_train)

    print("  - Prédiction...")
    y_pred = clf.predict(X_test)
    y_proba = clf.predict_proba(X_test)[:, 1]

    acc = accuracy_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_proba)

    accs.append(acc)
    aucs.append(auc)

    print(f"  → Accuracy split {split_id} : {acc:.3f}")
    print(f"  → AUC split {split_id}      : {auc:.3f}")

print("\n===== Résultats finaux (moyenne sur 10 splits) =====")
print(f"Accuracy : mean = {np.mean(accs):.3f}, std = {np.std(accs):.3f}")
print(f"AUC      : mean = {np.mean(aucs):.3f}, std = {np.std(aucs):.3f}")

Préparation des données...
Nombre de sujets : 243
Nombre total de features corr_* : 93961
Nombre de features après retrait des colonnes 100% NaN : 93096
Répartition SCHZ = 96, CONTROL = 147

Démarrage du cross-validation 10 splits...

  0%|          | 0/10 [00:00<?, ?it/s]

=== Split 1 / 10 ===
  - Entraînement du modèle (imputation + scaling + logreg)...

  0%|          | 0/10 [00:04<?, ?it/s]

KeyboardInterrupt:

In [26]:
### verison avec PCA

import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, roc_auc_score
from tqdm import tqdm

print("Préparation des données...")

# Toutes les colonnes corr_*
all_corr_cols = [c for c in df_all.columns if c.startswith("corr_")]
X_full = df_all[all_corr_cols]

# Garder seulement les colonnes avec au moins une valeur non-NaN
valid_mask = X_full.notna().any(axis=0)
corr_cols = list(X_full.columns[valid_mask])
X = X_full[corr_cols].values

# y = 1 pour SCHZ, 0 pour CONTROL
y = (df_all["diagnosis"] == "SCHZ").astype(int).values

print(f"Nombre de sujets : {len(y)}")
print(f"Nombre total de features corr_* : {len(all_corr_cols)}")
print(f"Nombre de features après retrait des colonnes 100% NaN : {len(corr_cols)}")
print(f"Répartition SCHZ = {y.sum()}, CONTROL = {len(y) - y.sum()}")

# 10 splits stratifiés, seed 42
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

clf_pca = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler(with_mean=True, with_std=True)),
    ("pca", PCA(
        n_components=100,
        svd_solver="randomized",
        random_state=42,
    )),
    ("logreg", LogisticRegression(
        penalty="l2",
        solver="saga",
        max_iter=5000,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )),
])

accs = []
aucs = []

print("\nDémarrage du cross-validation 10 splits (avec PCA 100 composantes)...\n")

for split_id, (train_idx, test_idx) in enumerate(tqdm(cv.split(X, y), total=10), start=1):

    print(f"\n=== Split {split_id} / 10 ===")

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    print("  - Entraînement du modèle (imputation + scaling + PCA + logreg)...")
    clf_pca.fit(X_train, y_train)

    print("  - Prédiction...")
    y_pred = clf_pca.predict(X_test)
    y_proba = clf_pca.predict_proba(X_test)[:, 1]

    acc = accuracy_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_proba)

    accs.append(acc)
    aucs.append(auc)

    print(f"  → Accuracy split {split_id} : {acc:.3f}")
    print(f"  → AUC split {split_id}      : {auc:.3f}")

print("\n===== Résultats finaux (moyenne sur 10 splits, PCA 100) =====")
print(f"Accuracy : mean = {np.mean(accs):.3f}, std = {np.std(accs):.3f}")
print(f"AUC      : mean = {np.mean(aucs):.3f}, std = {np.std(aucs):.3f}")

Préparation des données...
Nombre de sujets : 243
Nombre total de features corr_* : 93961
Nombre de features après retrait des colonnes 100% NaN : 93096
Répartition SCHZ = 96, CONTROL = 147

Démarrage du cross-validation 10 splits (avec PCA 100 composantes)...

  0%|          | 0/10 [00:00<?, ?it/s]

=== Split 1 / 10 ===
  - Entraînement du modèle (imputation + scaling + PCA + logreg)...
  - Prédiction...

 10%|█         | 1/10 [00:06<00:55,  6.16s/it]

  → Accuracy split 1 : 0.920
  → AUC split 1      : 0.980

=== Split 2 / 10 ===
  - Entraînement du modèle (imputation + scaling + PCA + logreg)...

 20%|██        | 2/10 [00:11<00:46,  5.78s/it]

  - Prédiction...
  → Accuracy split 2 : 0.680
  → AUC split 2      : 0.667

=== Split 3 / 10 ===
  - Entraînement du modèle (imputation + scaling + PCA + logreg)...

 30%|███       | 3/10 [00:17<00:39,  5.66s/it]

  - Prédiction...
  → Accuracy split 3 : 0.800
  → AUC split 3      : 0.860

=== Split 4 / 10 ===
  - Entraînement du modèle (imputation + scaling + PCA + logreg)...

 40%|████      | 4/10 [00:20<00:27,  4.63s/it]

  - Prédiction...
  → Accuracy split 4 : 0.708
  → AUC split 4      : 0.896

=== Split 5 / 10 ===
  - Entraînement du modèle (imputation + scaling + PCA + logreg)...

 50%|█████     | 5/10 [00:25<00:24,  4.86s/it]

  - Prédiction...
  → Accuracy split 5 : 0.833
  → AUC split 5      : 0.896

=== Split 6 / 10 ===
  - Entraînement du modèle (imputation + scaling + PCA + logreg)...

 60%|██████    | 6/10 [00:29<00:18,  4.60s/it]

  - Prédiction...
  → Accuracy split 6 : 0.708
  → AUC split 6      : 0.859

=== Split 7 / 10 ===
  - Entraînement du modèle (imputation + scaling + PCA + logreg)...

 70%|███████   | 7/10 [00:31<00:11,  3.80s/it]

  - Prédiction...
  → Accuracy split 7 : 0.708
  → AUC split 7      : 0.844

=== Split 8 / 10 ===
  - Entraînement du modèle (imputation + scaling + PCA + logreg)...

 80%|████████  | 8/10 [00:37<00:08,  4.35s/it]

  - Prédiction...
  → Accuracy split 8 : 0.708
  → AUC split 8      : 0.843

=== Split 9 / 10 ===
  - Entraînement du modèle (imputation + scaling + PCA + logreg)...

 90%|█████████ | 9/10 [00:42<00:04,  4.72s/it]

  - Prédiction...
  → Accuracy split 9 : 0.792
  → AUC split 9      : 0.857

=== Split 10 / 10 ===
  - Entraînement du modèle (imputation + scaling + PCA + logreg)...

100%|██████████| 10/10 [00:48<00:00,  4.84s/it]

  - Prédiction...
  → Accuracy split 10 : 0.708
  → AUC split 10      : 0.686

===== Résultats finaux (moyenne sur 10 splits, PCA 100) =====
Accuracy : mean = 0.757, std = 0.073
AUC      : mean = 0.839, std = 0.090

In [31]:
import pandas as pd
import numpy as np
import os
import warnings
from tqdm import tqdm
from pynm.pynm import PyNM

# --- RPY2 ---
import rpy2.robjects as robjects
from rpy2.robjects import r, pandas2ri, numpy2ri
from rpy2.robjects.conversion import localconverter

print("🚀 LANCEMENT DE LA PRODUCTION (100 MODÈLES) 🚀")

# ==============================================================================
# 1. CONFIGURATION ET DONNÉES
# ==============================================================================
# Config R
user_lib_path = os.path.abspath(os.path.expanduser("~/R_libs"))
r(f'.libPaths(c("{user_lib_path}", .libPaths()))')
r('library("gamlss")')

# Patch rpy2
def do_nothing(): pass
numpy2ri.activate = do_nothing
pandas2ri.activate = do_nothing
numpy2ri.deactivate = do_nothing
pandas2ri.deactivate = do_nothing

# Vérification Données
if 'df_pynm' not in locals():
    raise NameError("df_pynm manquant.")
if 'group' not in df_pynm.columns:
    df_pynm["group"] = df_pynm["diagnosis"].map({"CONTROL": 0, "SCHZ": 1})

# ==============================================================================
# 2. TRANSFERT DES DONNÉES (UNE SEULE FOIS)
# ==============================================================================
print("1. Transfert du dataset vers R...")
with localconverter(robjects.default_converter + pandas2ri.converter):
    r.assign("donnees_globales", df_pynm)

# On prépare le data.frame côté R une bonne fois pour toutes
r('df_global <- as.data.frame(donnees_globales)')
# On prépare le sous-ensemble d'entraînement côté R
r('df_train_global <- df_global[df_global$group == 0, ]')

print(f"   -> Dataset R prêt. Training set size: {r('nrow(df_train_global)')[0]}")

# ==============================================================================
# 3. BOUCLE D'ENTRAÎNEMENT
# ==============================================================================
print(f"2. Calcul des Z-scores pour {len(cols_pca)} composantes...")
warnings.filterwarnings('ignore')

df_deviations = pd.DataFrame(index=df_pynm.index)
df_deviations["diagnosis"] = df_pynm["diagnosis"]
if "site_id" in df_all.columns:
     df_deviations["site_id"] = df_all["site_id"].values[df_pynm.index]

success_count = 0

for pc_col in tqdm(cols_pca):
    try:
        # Script R optimisé : il utilise les objets globaux 'df_global' et 'df_train_global'
        # Plus besoin de transfert de données, c'est instantané.
        script_R = f"""
        # 1. Fit sur le subset pré-calculé
        # On utilise as.formula pour gérer dynamiquement le nom de la colonne
        fmla <- as.formula("{pc_col} ~ age + c(gender)")
        
        m <- gamlss(fmla, sigma.formula=~1, family=NO, data=df_train_global, trace=FALSE)
        
        # 2. Predict sur le dataset complet
        mu <- predict(m, newdata=df_global, what="mu", type="response")
        sigma <- predict(m, newdata=df_global, what="sigma", type="response")
        
        # 3. Export vecteurs
        res <- list(mu=as.vector(mu), sigma=as.vector(sigma))
        """
        
        # Exécution
        r(script_R)
        
        # Récupération résultats
        res_r = r['res']
        mu_vals = np.array(res_r.rx2('mu'))
        sigma_vals = np.array(res_r.rx2('sigma'))
        
        # Calcul Z-Score Python
        y_real = df_pynm[pc_col].values
        z_scores = (y_real - mu_vals) / sigma_vals
        
        df_deviations[f"z_{pc_col}"] = z_scores
        success_count += 1
        
    except Exception as e:
        # print(f"Erreur sur {pc_col}: {e}") # Décommenter si besoin
        df_deviations[f"z_{pc_col}"] = np.nan

# ==============================================================================
# 4. FIN
# ==============================================================================
print(f"\nTraitement terminé. Succès : {success_count}/{len(cols_pca)}")

output_file = "deviations_gamlss_pca100_final.csv"
df_deviations.to_csv(output_file, index=False)
print(f"✅ Résultats sauvegardés dans : {output_file}")

display(df_deviations.head())

🚀 LANCEMENT DE LA PRODUCTION (100 MODÈLES) 🚀
1. Transfert du dataset vers R...
   -> Dataset R prêt. Training set size: 147
2. Calcul des Z-scores pour 100 composantes...

100%|██████████| 100/100 [00:00<00:00, 114.44it/s]

Traitement terminé. Succès : 100/100
✅ Résultats sauvegardés dans : deviations_gamlss_pca100_final.csv

,diagnosis,site_id,z_PC_0,z_PC_1,z_PC_2,z_PC_3,z_PC_4,z_PC_5,z_PC_6,z_PC_7,...,z_PC_90,z_PC_91,z_PC_92,z_PC_93,z_PC_94,z_PC_95,z_PC_96,z_PC_97,z_PC_98,z_PC_99
0,CONTROL,ds000030,0.363483,0.840815,-0.306652,-0.328988,-0.430902,0.310294,1.573618,-0.880009,...,0.073930,-0.650080,-0.790196,0.278876,0.522251,-0.541432,2.280380,0.648023,0.427116,0.035636
1,SCHZ,ds000030,-0.642432,1.191071,0.799580,0.892923,-1.608257,-1.384023,1.536559,-1.268676,...,1.468787,-0.285365,2.019978,0.559362,-1.902262,-0.625672,-0.673027,1.307198,-0.944824,0.183208
2,CONTROL,ds000030,1.074312,0.097995,-1.066899,-0.096474,-0.654275,-0.063311,0.635467,0.450198,...,1.283304,-0.407962,0.379400,1.534798,-1.108395,-2.168359,-0.107351,0.746908,-1.235526,-0.715130
3,CONTROL,ds000030,-0.507505,-0.114991,-0.240426,-0.252122,-0.160721,-0.230898,0.438215,-1.401483,...,-2.093082,2.164401,0.922150,-0.687594,-0.244654,0.424082,-0.806400,-1.095066,0.327873,-1.236043
4,CONTROL,ds000030,0.329346,-0.016210,1.100266,0.293714,0.057059,0.469964,1.068378,0.360461,...,-0.511953,-2.128051,0.079198,0.877427,-0.188204,0.408689,-0.570078,-0.611484,-1.243933,-0.274027